name: scan_station
description: 站台扫码工具 1‑8站台，扫码、导出剪贴板、导出表格
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.1.1
  csv: ^6.0.0
  share_plus: ^10.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
