name: Build-Scan-Station-APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter 3.22.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: stable
          cache: true

      - name: Setup Android SDK, auto accept licenses
        uses: android-actions/setup-android@v3
        with:
          accept-licenses: true

      - name: flutter pub get
        run: flutter pub get

      - name: Generate Isar Database Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: disable analytics
        run: flutter config --no-analytics

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v4
        with:
          name: scan-station-apk-output
          path: build/app/outputs/flutter-apk/app-release.apk